<Window
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:attributemodifier"
        xmlns:UIControls="clr-namespace:Tekla.Structures.Dialog.UIControls;assembly=Tekla.Structures.Dialog" xmlns:Catalogs="clr-namespace:Tekla.Structures.Catalogs;assembly=Tekla.Structures.Catalogs" x:Class="attributemodifier.MainWindow"
        mc:Ignorable="d"
        Title="Attribute modifier" Height="519.667" Width="400" Background="White" Foreground="Black"   ResizeMode="NoResize" SizeToContent="WidthAndHeight" WindowStyle="None" WindowStartupLocation="CenterOwner">
    <Grid Margin="0,0,0,69" RenderTransformOrigin="0.492,1.002">

        <TabControl Width="400" Margin="0,0,0,-67">
            <TabItem Header="PARTS" FontWeight="Bold" FontSize="17"  Foreground="#FF28458C" Margin="0,-2,-1,0" Width="75">
                <Grid>
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="112*"/>
                        <ColumnDefinition Width="8*"/>
                        <ColumnDefinition Width="12*"/>
                        <ColumnDefinition Width="27*"/>
                        <ColumnDefinition Width="197*"/>
                        <ColumnDefinition Width="38*"/>
                    </Grid.ColumnDefinitions>

                    <TextBlock HorizontalAlignment="Left" Margin="10,159,0,0" TextWrapping="Wrap" VerticalAlignment="Top" RenderTransformOrigin="0.174,0.627" FontSize="14" FontWeight="Bold" Foreground="#FF28458C"><Run Text="Name"/></TextBlock>
                    <TextBlock HorizontalAlignment="Left" Margin="10,192,0,0" TextWrapping="Wrap" Text="Profile" VerticalAlignment="Top" Width="54" RenderTransformOrigin="-0.074,0.375" FontSize="14" Foreground="#FF28458C" FontWeight="Bold"/>
                    <TextBlock HorizontalAlignment="Left" Margin="10,227,0,0" TextWrapping="Wrap" VerticalAlignment="Top" Width="54" FontSize="14" RenderTransformOrigin="0.494,1.182" FontWeight="Bold" Foreground="#FF28458C"><Run Text="Finish"/></TextBlock>
                    <TextBox x:Name ="Nametextbox" Style="{StaticResource Input}" Height="25" Margin="0,156,0,0" TextWrapping="Wrap" VerticalAlignment="Top" Width="250" TextChanged="TextBox_TextChanged" HorizontalAlignment="Left" Grid.Column="3" Grid.ColumnSpan="3" FontSize="15" SelectionBrush="#FF004AFF" BorderThickness="0,0,0,1"/>
                    <TextBox x:Name ="Profiletextbox" Style="{StaticResource Input}" Height="25" Margin="0,190,0,0" TextWrapping="Wrap" VerticalAlignment="Top" Width="250" TextChanged="TextBox_TextChanged" HorizontalAlignment="Left" Grid.Column="3" Grid.ColumnSpan="3" FontSize="15" BorderThickness="0,0,0,1"/>
                    <TextBox x:Name ="Finishtextbox" Style="{StaticResource Input}" Height="25" Margin="0,224,0,0" TextWrapping="Wrap" VerticalAlignment="Top" Width="250" TextChanged="TextBox_TextChanged" HorizontalAlignment="Left" Grid.Column="3"  Grid.ColumnSpan="3" FontSize="15" BorderThickness="0,0,0,1"/>
                    <TextBlock HorizontalAlignment="Left" Margin="10,129,0,0" TextWrapping="Wrap" VerticalAlignment="Top" RenderTransformOrigin="-0.481,1.375" FontWeight="Bold" FontSize="17" Width="178" Grid.ColumnSpan="5" Foreground="#FF052061"><Run Text="Attributes"/></TextBlock>
                    <TextBlock HorizontalAlignment="Left" Margin="10,293,0,0" TextWrapping="Wrap" VerticalAlignment="Top" Width="54" RenderTransformOrigin="0.944,6.375" Text="Class" FontSize="14" FontWeight="Bold" Foreground="#FF28458C"/>
                    <TextBox x:Name ="Classtextbox" Style="{StaticResource Input}" Height="25" Margin="0,290,0,0" TextWrapping="Wrap" VerticalAlignment="Top" Width="250" TextChanged="TextBox_TextChanged" HorizontalAlignment="Left" Grid.Column="3" Grid.ColumnSpan="3" FontSize="15" BorderThickness="0,0,0,1"/>
                    <TextBlock HorizontalAlignment="Left" Margin="10,320,0,0" TextWrapping="Wrap" Text="User-defined attributes" VerticalAlignment="Top" RenderTransformOrigin="-0.481,1.375" FontWeight="Bold" FontSize="17" Width="229" Grid.ColumnSpan="5" Foreground="#FF052061"/>
                    <TextBlock HorizontalAlignment="Left" Margin="10,354,0,0" TextWrapping="Wrap" VerticalAlignment="Top" Width="98" RenderTransformOrigin="0.944,6.375" Text="Comment" FontSize="14" FontWeight="Bold" Foreground="#FF28458C"/>
                    <TextBlock HorizontalAlignment="Left" Margin="10,384,0,0" TextWrapping="Wrap" VerticalAlignment="Top" Width="154" RenderTransformOrigin="0.944,6.375" Text="Bought Out Item Name" FontSize="14" Grid.ColumnSpan="5" FontWeight="Bold" Foreground="#FF28458C"/>
                    <TextBox x:Name ="Boinametextbox" Style="{StaticResource Input}" Height="25" Margin="35,382,0,0" TextWrapping="Wrap" VerticalAlignment="Top" Width="190" TextChanged="TextBox_TextChanged" HorizontalAlignment="Left" Grid.Column="4" Grid.ColumnSpan="2" FontSize="15" BorderThickness="0,0,0,1"/>
                    <TextBox x:Name ="Commenttextbox" Style="{StaticResource Input}" Height="25" Margin="35,351,0,0" TextWrapping="Wrap" VerticalAlignment="Top" Width="190" TextChanged="TextBox_TextChanged" HorizontalAlignment="Left" FontSize="15" Grid.Column="4" Grid.ColumnSpan="2" BorderThickness="0,0,0,1"/>
                    <TextBlock HorizontalAlignment="Left" Margin="10,15,0,0" TextWrapping="Wrap" VerticalAlignment="Top" RenderTransformOrigin="-0.481,1.375" Width="299" FontWeight="Bold" FontSize="17" Grid.ColumnSpan="5" Foreground="#FF052061"><Run Text="Numbering series"/></TextBlock>
                    <TextBlock HorizontalAlignment="Left" Margin="10,68,0,0" TextWrapping="Wrap" Text="Part" VerticalAlignment="Top" RenderTransformOrigin="-0.481,1.375" Width="128" FontSize="14" Grid.ColumnSpan="4" FontWeight="Bold" Foreground="#FF28458C"/>
                    <TextBlock HorizontalAlignment="Left" Margin="10,100,0,0" TextWrapping="Wrap" Text="Assembly" VerticalAlignment="Top" RenderTransformOrigin="-0.481,1.375" Width="128" FontSize="14" Grid.ColumnSpan="4" FontWeight="Bold" Foreground="#FF28458C"/>
                    <TextBox x:Name ="Partprefixtextbox" Style="{StaticResource Input}" Height="25" Margin="0,65,0,0" TextWrapping="Wrap" VerticalAlignment="Top" Width="110" TextChanged="TextBox_TextChanged" HorizontalAlignment="Left" Grid.Column="3" FontSize="15" BorderThickness="0,0,0,1" Grid.ColumnSpan="2"/>
                    <TextBox x:Name ="Assemblyprefixtextbox" Style="{StaticResource Input}" Height="25" Margin="0,99,0,0" TextWrapping="Wrap" VerticalAlignment="Top" Width="110" TextChanged="TextBox_TextChanged" HorizontalAlignment="Left" RenderTransformOrigin="0.518,1" Grid.Column="3" FontSize="15" BorderThickness="0,0,0,1" Grid.ColumnSpan="2"/>
                    <TextBox x:Name ="Partstartnumbertextbox" Style="{StaticResource Input}" Height="25" Margin="114,65,0,0" TextWrapping="Wrap" VerticalAlignment="Top" Width="110" TextChanged="TextBox_TextChanged" HorizontalAlignment="Left" Grid.Column="4" Grid.ColumnSpan="2" FontSize="15" BorderThickness="0,0,0,1"/>
                    <TextBox x:Name ="Assemblystartnumbertextbox" Style="{StaticResource Input}" Height="25" Margin="114,99,0,0" TextWrapping="Wrap" VerticalAlignment="Top" Width="110" TextChanged="TextBox_TextChanged" HorizontalAlignment="Left" RenderTransformOrigin="0.501,1.292" Grid.Column="4" Grid.ColumnSpan="2" FontSize="15" BorderThickness="0,0,0,1"/>
                    <TextBlock HorizontalAlignment="Left" Margin="10,260,0,0" TextWrapping="Wrap" VerticalAlignment="Top" Width="77" RenderTransformOrigin="0.944,6.375" Text="Material" FontSize="14" FontWeight="Bold" Foreground="#FF28458C"/>
                    <TextBox x:Name ="Materialtextbox" Style="{StaticResource Input}" Height="25" Margin="0,257,0,0" TextWrapping="Wrap" VerticalAlignment="Top" Width="250" TextChanged="TextBox_TextChanged" HorizontalAlignment="Left" Grid.Column="3" Grid.ColumnSpan="3" FontSize="15" BorderThickness="0,0,0,1"/>
                    <TextBlock Margin="0,41,-61,0" TextWrapping="Wrap" Text="Prefix:" VerticalAlignment="Top" RenderTransformOrigin="-0.481,1.375" FontSize="14" Grid.ColumnSpan="3" Grid.Column="3" FontWeight="Bold" Foreground="#FF28458C"/>
                    <TextBlock HorizontalAlignment="Left" Margin="114,41,-7,0" TextWrapping="Wrap" Text="Start number:" VerticalAlignment="Top" RenderTransformOrigin="-0.481,1.375" Width="128" FontSize="14" Grid.Column="4" Grid.ColumnSpan="2" FontWeight="Bold" Foreground="#FF28458C"/>
                    <CheckBox  x:Name="checkbox_partstartnumber" Grid.Column="4" HorizontalAlignment="Left" Margin="90,68,0,0" VerticalAlignment="Top" FontSize="0.01" BorderBrush="#FF052061">
                        <CheckBox.LayoutTransform>
                            <ScaleTransform ScaleX="1.2" ScaleY="1.2"/>
                        </CheckBox.LayoutTransform>
                    </CheckBox>
                    <CheckBox  x:Name="checkbox_assstartnumber" Grid.Column="4" HorizontalAlignment="Left" Margin="90,103,0,0" VerticalAlignment="Top" FontSize="0.01" BorderBrush="#FF052061">
                        <CheckBox.LayoutTransform>
                            <ScaleTransform ScaleX="1.2" ScaleY="1.2"/>
                        </CheckBox.LayoutTransform>
                    </CheckBox>
                    <CheckBox  x:Name="checkbox_partprefix" HorizontalAlignment="Left" Margin="106,68,0,0" VerticalAlignment="Top" FontSize="0.01" Grid.ColumnSpan="3" BorderBrush="#FF052061">
                        <CheckBox.LayoutTransform>
                            <ScaleTransform ScaleX="1.2" ScaleY="1.2"/>
                        </CheckBox.LayoutTransform>
                    </CheckBox>
                    <CheckBox  x:Name="checkbox_assprefix" HorizontalAlignment="Left" Margin="106,103,0,0" VerticalAlignment="Top" FontSize="0.01" Grid.ColumnSpan="3" BorderBrush="#FF052061">
                        <CheckBox.LayoutTransform>
                            <ScaleTransform ScaleX="1.2" ScaleY="1.2"/>
                        </CheckBox.LayoutTransform>
                    </CheckBox>
                    <CheckBox  x:Name="checkbox_partname" HorizontalAlignment="Left" Margin="106,159,0,0" VerticalAlignment="Top" FontSize="0.01" Grid.ColumnSpan="3" BorderBrush="#FF052061">
                        <CheckBox.LayoutTransform>
                            <ScaleTransform ScaleX="1.2" ScaleY="1.2"/>
                        </CheckBox.LayoutTransform>
                    </CheckBox>
                    <CheckBox  x:Name="checkbox_partprofile" HorizontalAlignment="Left" Margin="106,193,0,0" VerticalAlignment="Top" FontSize="0.01" Grid.ColumnSpan="3" BorderBrush="#FF052061">
                        <CheckBox.LayoutTransform>
                            <ScaleTransform ScaleX="1.2" ScaleY="1.2"/>
                        </CheckBox.LayoutTransform>
                    </CheckBox>
                    <CheckBox  x:Name="checkbox_finish" HorizontalAlignment="Left" Margin="106,226,0,0" VerticalAlignment="Top" FontSize="0.01" Grid.ColumnSpan="3" BorderBrush="#FF052061">
                        <CheckBox.LayoutTransform>
                            <ScaleTransform ScaleX="1.2" ScaleY="1.2"/>
                        </CheckBox.LayoutTransform>
                    </CheckBox>
                    <CheckBox  x:Name="checkbox_material" HorizontalAlignment="Left" Margin="106,260,0,0" VerticalAlignment="Top" FontSize="0.01" Grid.ColumnSpan="3" BorderBrush="#FF052061">
                        <CheckBox.LayoutTransform>
                            <ScaleTransform ScaleX="1.2" ScaleY="1.2"/>
                        </CheckBox.LayoutTransform>
                    </CheckBox>
                    <CheckBox  x:Name="checkbox_class" HorizontalAlignment="Left" Margin="106,293,0,0" VerticalAlignment="Top" FontSize="0.01" Grid.ColumnSpan="3" BorderBrush="#FF052061">
                        <CheckBox.LayoutTransform>
                            <ScaleTransform ScaleX="1.2" ScaleY="1.2"/>
                        </CheckBox.LayoutTransform>
                    </CheckBox>
                    <CheckBox  x:Name="checkbox_comment"  HorizontalAlignment="Left" Margin="10,356,0,0" VerticalAlignment="Top" FontSize="0.01" Grid.Column="4" BorderBrush="#FF052061">
                        <CheckBox.LayoutTransform>
                            <ScaleTransform ScaleX="1.2" ScaleY="1.2"/>
                        </CheckBox.LayoutTransform>
                    </CheckBox>
                    <CheckBox  x:Name="checkbox_boi" Margin="10,386,169,0" VerticalAlignment="Top" FontSize="0.01" Grid.Column="4" Height="16" BorderBrush="#FF052061">
                        <CheckBox.LayoutTransform>
                            <ScaleTransform ScaleX="1.2" ScaleY="1.2"/>
                        </CheckBox.LayoutTransform>
                    </CheckBox>

                    <Button Margin="8,428,4,11"  Content="Select all" Click="Button_Click_2"  BorderThickness="2" Width="100" Height="40.1" RenderTransformOrigin="0.36,0.374" Background="White" BorderBrush="#FF28458C" Foreground="#FF28458C" FontWeight="Bold" FontSize="16" />
                    <Button Margin="2,428,134,11" RenderTransformOrigin="0.5,0.5" Content="Unselect all" BorderThickness="2" Grid.Column="2" Width="100" Height="40" Grid.ColumnSpan="3" Click="Button_Click_5" BorderBrush="#FF28458C" Background="White" Foreground="#FF28458C" FontWeight="Bold" FontSize="16" />
                    <Button Content="..." HorizontalAlignment="Left" BorderThickness="1" Margin="74,258,0,0" VerticalAlignment="Top" Width="23" Click="Button_Click_6" Height="23" BorderBrush="#FF0B1A40" Background="White" RenderTransformOrigin="0.543,0.754"/>
                    <Button Content="..." HorizontalAlignment="Left" Margin="74,190,0,0" VerticalAlignment="Top" Width="23" Height="23" Foreground="#FF0B1A40" BorderBrush="#FF0B1A40" Background="White" FontSize="14" RenderTransformOrigin="0.942,0.739" Click="Button_Click_7"/>

                </Grid>
            </TabItem>
            <TabItem Header="BOLTS" FontWeight="Bold" FontSize="17"  Foreground="#FF28458C" Margin="13,-2,-51,0">
                <Grid>
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="16*"/>
                        <ColumnDefinition Width="11*"/>
                        <ColumnDefinition Width="11*"/>
                        <ColumnDefinition Width="9*"/>
                        <ColumnDefinition Width="5*"/>
                        <ColumnDefinition Width="342*"/>
                    </Grid.ColumnDefinitions>
                    <TextBox x:Name="boltcutlengthtextbox" Style="{StaticResource Input}" Margin="187,129,35,0" TextWrapping="Wrap" VerticalAlignment="Top" Width="120" Grid.Column="5" FontSize="15" Height="25" BorderThickness="0,0,0,1" ClipToBounds="True"/>
                    <TextBlock HorizontalAlignment="Left" Margin="119,0,0,418" TextWrapping="Wrap" Text="Size" VerticalAlignment="Bottom" Grid.Column="5" FontSize="14" FontWeight="Bold" Foreground="#FF28458C"/>
                    <TextBlock HorizontalAlignment="Left" Margin="88,72,0,0" TextWrapping="Wrap" VerticalAlignment="Top" RenderTransformOrigin="0.528,-0.47" Grid.Column="5" FontSize="14" FontWeight="Bold" Foreground="#FF28458C"><Run Text="Standard"/></TextBlock>
                    <TextBlock HorizontalAlignment="Left" Margin="6,102,0,0" TextWrapping="Wrap" Text="Bolt type (site/workshop)" VerticalAlignment="Top" Grid.Column="2" FontSize="14" FontWeight="Bold" Foreground="#FF28458C" Grid.ColumnSpan="4"/>
                    <TextBlock HorizontalAlignment="Left" Margin="10,16,0,0" TextWrapping="Wrap" VerticalAlignment="Top" RenderTransformOrigin="-0.481,1.375" Width="299" FontWeight="Bold" FontSize="17" Grid.ColumnSpan="6" Foreground="#FF052061"><Run Text="Bolt"/></TextBlock>
                    <TextBlock HorizontalAlignment="Left" Margin="79,132,0,0" TextWrapping="Wrap" Text="Cut length" VerticalAlignment="Top" RenderTransformOrigin="0.541,-0.123" Grid.Column="5" FontSize="14" FontWeight="Bold" Foreground="#FF28458C"/>
                    <TextBlock HorizontalAlignment="Left" Margin="70,162,0,0" TextWrapping="Wrap" Text="Extra length" VerticalAlignment="Top" Grid.Column="5" FontSize="14" FontWeight="Bold" Foreground="#FF28458C"/>
                    <ComboBox x:Name="combobox_bolttype" Grid.Column="5" HorizontalAlignment="Left" Margin="187,99,0,0" VerticalAlignment="Top" Width="120" Height="25" FontSize="14"/>
                    <TextBox x:Name ="boltextralengthtextbox" Style="{StaticResource Input}" HorizontalAlignment="Left" Margin="187,159,0,0" TextWrapping="Wrap"  VerticalAlignment="Top" Width="120" Grid.Column="5" FontSize="15" Height="25" BorderThickness="0,0,0,1" ClipToBounds="True"/>
                    <TextBlock HorizontalAlignment="Left" Margin="11,228,0,0" TextWrapping="Wrap" Text="Holes" VerticalAlignment="Top" RenderTransformOrigin="-0.481,1.375" Width="299" FontWeight="Bold" FontSize="17" Grid.ColumnSpan="6" Foreground="#FF052061"/>
                    <TextBox x:Name="bolttolerancetextbox" Style="{StaticResource Input}" HorizontalAlignment="Left" Margin="187,250,0,0" TextWrapping="Wrap"  VerticalAlignment="Top" Width="120" Grid.Column="5" FontSize="15" Height="25" BorderThickness="0,0,0,1"/>

                    <TextBox x:Name="boltslothole_x_textbox" Style="{StaticResource Input}" Margin="187,310,35,0" TextWrapping="Wrap"  VerticalAlignment="Top" Width="120" Grid.Column="5" FontSize="15" Height="25" BorderThickness="0,0,0,1"/>
                    <TextBox x:Name="boltslothole_y_textbox" Style="{StaticResource Input}" Margin="187,340,35,0" TextWrapping="Wrap"  VerticalAlignment="Top" Width="120" Grid.Column="5" FontSize="15" Height="25" BorderThickness="0,0,0,1"/>
                    <TextBlock HorizontalAlignment="Left" Margin="85,254,0,0" TextWrapping="Wrap" Text="Tolerance" VerticalAlignment="Top" RenderTransformOrigin="0.498,0.251" Grid.Column="5" FontSize="14" FontWeight="Bold" Foreground="#FF28458C"/>
                    <TextBlock HorizontalAlignment="Left" Margin="100,284,0,0" TextWrapping="Wrap" Text="Slotted" VerticalAlignment="Top" RenderTransformOrigin="0.498,0.251" Grid.Column="5" FontSize="14" FontWeight="Bold" Foreground="#FF28458C"/>
                    <TextBlock HorizontalAlignment="Left" Margin="57,313,0,0" TextWrapping="Wrap" Text="Slotted hole X" VerticalAlignment="Top" RenderTransformOrigin="0.498,0.251" Grid.Column="5" FontSize="14" FontWeight="Bold" Foreground="#FF28458C"/>
                    <TextBlock HorizontalAlignment="Left" Margin="57,343,0,0" TextWrapping="Wrap" Text="Slotted hole Y" VerticalAlignment="Top" RenderTransformOrigin="0.498,0.251" Grid.Column="5" FontSize="14" FontWeight="Bold" Foreground="#FF28458C"/>
                    <UIControls:WpfBoltCatalogSize x:Name="boltcatalogsize" HorizontalAlignment="Left" Margin="187,39,0,0" VerticalAlignment="Top" Width="120" Grid.Column="5" ItemsSource="{Binding BoltSizes, ElementName=boltcatalog_standard}" FontSize="14" Height="25"/>
                    <UIControls:WpfBoltCatalogStandard x:Name="boltcatalog_standard"   HorizontalAlignment="Left" Margin="187,69,0,0" VerticalAlignment="Top" Width="120" Grid.Column="5" FontSize="14" Height="25" />
                    <CheckBox  x:Name="checkbox_boltsize" Grid.Column="5" HorizontalAlignment="Center" Margin="0,44,0,0" VerticalAlignment="Top" FontSize="0.01" BorderBrush="#FF052061">
                        <CheckBox.LayoutTransform>
                            <ScaleTransform ScaleX="1.2" ScaleY="1.2"/>
                        </CheckBox.LayoutTransform>
                    </CheckBox>
                    <CheckBox  x:Name="checkbox_boltstandard" Grid.Column="5" HorizontalAlignment="Center" Margin="0,73,0,0" VerticalAlignment="Top" FontSize="0.01" BorderBrush="#FF052061">
                        <CheckBox.LayoutTransform>
                            <ScaleTransform ScaleX="1.2" ScaleY="1.2"/>
                        </CheckBox.LayoutTransform>
                    </CheckBox>
                    <CheckBox  x:Name="checkbox_bolttype" Grid.Column="5" HorizontalAlignment="Center" Margin="0,103,0,0" VerticalAlignment="Top" FontSize="0.01" Width="16" Height="16" BorderBrush="#FF052061">
                        <CheckBox.LayoutTransform>
                            <ScaleTransform ScaleX="1.2" ScaleY="1.2"/>
                        </CheckBox.LayoutTransform>
                    </CheckBox>
                    <CheckBox  x:Name="checkbox_cutlength" Grid.Column="5" HorizontalAlignment="Center" Margin="0,133,0,0" VerticalAlignment="Top" FontSize="0.01" BorderBrush="#FF052061">
                        <CheckBox.LayoutTransform>
                            <ScaleTransform ScaleX="1.2" ScaleY="1.2"/>
                        </CheckBox.LayoutTransform>
                    </CheckBox>
                    <CheckBox  x:Name="checkbox_extralength" Grid.Column="5" HorizontalAlignment="Center" Margin="0,164,0,0" VerticalAlignment="Top" FontSize="0.01" BorderBrush="#FF052061">
                        <CheckBox.LayoutTransform>
                            <ScaleTransform ScaleX="1.2" ScaleY="1.2"/>
                        </CheckBox.LayoutTransform>
                    </CheckBox>
                    <CheckBox  x:Name="checkbox_tolerance" Grid.Column="5" HorizontalAlignment="Center" Margin="0,254,0,0" VerticalAlignment="Top" FontSize="0.01" BorderBrush="#FF052061">
                        <CheckBox.LayoutTransform>
                            <ScaleTransform ScaleX="1.2" ScaleY="1.2"/>
                        </CheckBox.LayoutTransform>
                    </CheckBox>
                    <CheckBox  x:Name="checkbox_slotted" Grid.Column="5" HorizontalAlignment="Center" Margin="0,284,0,0" VerticalAlignment="Top" FontSize="0.01" BorderBrush="#FF052061">
                        <CheckBox.LayoutTransform>
                            <ScaleTransform ScaleX="1.2" ScaleY="1.2"/>
                        </CheckBox.LayoutTransform>
                    </CheckBox>
                    <CheckBox  x:Name="checkbox_slotholex" Grid.Column="5" HorizontalAlignment="Center" Margin="0,314,0,0" VerticalAlignment="Top" FontSize="0.01" BorderBrush="#FF052061">
                        <CheckBox.LayoutTransform>
                            <ScaleTransform ScaleX="1.2" ScaleY="1.2"/>
                        </CheckBox.LayoutTransform>
                    </CheckBox>
                    <CheckBox  x:Name="checkbox_slotholey" Grid.Column="5" HorizontalAlignment="Center" Margin="0,343,0,0" VerticalAlignment="Top" FontSize="0.01" Width="16" Height="16" BorderBrush="#FF052061">
                        <CheckBox.LayoutTransform>
                            <ScaleTransform ScaleX="1.2" ScaleY="1.2"/>
                        </CheckBox.LayoutTransform>
                    </CheckBox>
                    <Button Margin="8,430,286,13" Content="Select all" Click="Button_Click_1" Width="100" Height="40" BorderThickness="2" Grid.ColumnSpan="6" Foreground="#FF28458C" Background="White" BorderBrush="#FF28458C" FontWeight="Bold" FontSize="16" />
                    <Button Grid.Column="5" Margin="70,428,172,11" RenderTransformOrigin="0.5,0.5" Content="Unselect all" BorderThickness="2" Click="Button_Click_4" Width="100" Height="40" Foreground="#FF28458C" BorderBrush="#FF28458C" Background="White" FontWeight="Bold" FontSize="16" />
                    <ComboBox x:Name="combobox_slotted" Grid.Column="5" HorizontalAlignment="Left" Margin="187,280,0,0" VerticalAlignment="Top" Width="120" Height="25" FontSize="14"/>
                    <TextBlock HorizontalAlignment="Left" Margin="73,192,0,0" TextWrapping="Wrap" Text="Stud length" VerticalAlignment="Top" RenderTransformOrigin="0.498,0.251" Grid.Column="5" FontSize="14" FontWeight="Bold" Foreground="#FF28458C"/>
                    <CheckBox x:Name="checkbox_studlength" Grid.Column="5" HorizontalAlignment="Center" Margin="0,193,0,0" VerticalAlignment="Top" BorderBrush="#FF052061">
                        <CheckBox.LayoutTransform>
                            <ScaleTransform ScaleX="1.2" ScaleY="1.2"/>
                        </CheckBox.LayoutTransform>
                    </CheckBox>
                    <TextBox x:Name="studlength_textbox" Style="{StaticResource Input}" Grid.Column="5" HorizontalAlignment="Left" Height="25" Margin="187,189,0,0" TextWrapping="Wrap"  VerticalAlignment="Top" Width="120" FontSize="15" BorderThickness="0,0,0,1" ClipToBounds="True"/>
                    <TextBlock HorizontalAlignment="Left" Margin="52,373,0,0" TextWrapping="Wrap" Text="Plain hole type" VerticalAlignment="Top" RenderTransformOrigin="0.498,0.251" Grid.Column="5" FontSize="14" FontWeight="Bold" Foreground="#FF28458C"/>


                    <CheckBox x:Name="checkbox_plainholetype"  Grid.Column="5" HorizontalAlignment="Center" Margin="0,374,0,0" VerticalAlignment="Top" Width="16" Height="16" BorderBrush="#FF052061">
                        <CheckBox.LayoutTransform>
                            <ScaleTransform ScaleX="1.2" ScaleY="1.2"/>
                        </CheckBox.LayoutTransform>
                    </CheckBox>
                    <ComboBox x:Name="combobox_plainholetype" Grid.Column="5" HorizontalAlignment="Left" Margin="187,370,0,0" VerticalAlignment="Top" Width="120" Height="25" FontSize="14"/>

                </Grid>
            </TabItem>

        </TabControl>

        <Button Content="Modify" HorizontalAlignment="Left" Margin="284,463,0,-52" Width="100" Click="Button_Click"  BorderThickness="2" RenderTransformOrigin="0.5,0.5" Height="40" VerticalAlignment="Top" BorderBrush="#FF28458C" Background="White" Foreground="#FF28458C" FontWeight="Bold" FontSize="16">
            <Button.RenderTransform>
                <TransformGroup>
                    <ScaleTransform/>
                    <SkewTransform/>
                    <RotateTransform Angle="0.084"/>
                    <TranslateTransform/>
                </TransformGroup>
            </Button.RenderTransform>
        </Button>
        <Button Content="X" HorizontalAlignment="Left" Margin="342,0,0,0" VerticalAlignment="Top" Width="58" FontSize="16" Height="29" FontWeight="Bold"  FontFamily="Arial Black" Background="#FFFF5353" AutomationProperties.Name="shutdownbutton" Click="Button_Click_3" BorderBrush="#FFDE6868"/>
    </Grid>
</Window>
