<Window
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:attributemodifier"
        xmlns:UIControls="clr-namespace:Tekla.Structures.Dialog.UIControls;assembly=Tekla.Structures.Dialog" x:Class="attributemodifier.MainWindow"
        mc:Ignorable="d"
        Title="Attribute modifier" Height="508.667" Width="400"  Background="White" Foreground="Black" BorderThickness="0"  ResizeMode="NoResize" SizeToContent="WidthAndHeight" WindowStyle="None" WindowStartupLocation="CenterOwner">
    <Grid Margin="0,0,0,69" RenderTransformOrigin="0.492,1.002">

        <TabControl Width="400" Margin="0,0,0,-67">
            <TabItem Header="Parts" Margin="0,-2,-1,0" Width="75">
                <Grid>
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="56*"/>
                        <ColumnDefinition Width="4*"/>
                        <ColumnDefinition Width="6*"/>
                        <ColumnDefinition Width="131*"/>
                    </Grid.ColumnDefinitions>

                    <TextBlock HorizontalAlignment="Left" Margin="13,136,0,0" TextWrapping="Wrap" VerticalAlignment="Top" RenderTransformOrigin="0.174,0.627" FontSize="14"><Run Text="Name"/></TextBlock>
                    <TextBlock HorizontalAlignment="Left" Margin="13,170,0,0" TextWrapping="Wrap" Text="Profile" VerticalAlignment="Top" Width="54" RenderTransformOrigin="-0.074,0.375" FontSize="14"/>
                    <TextBlock HorizontalAlignment="Left" Margin="13,204,0,0" TextWrapping="Wrap" VerticalAlignment="Top" Width="54" FontSize="14" RenderTransformOrigin="0.494,1.182"><Run Text="Finish"/></TextBlock>
                    <TextBox x:Name ="Nametextbox" Height="20" Margin="8,136,0,0" TextWrapping="Wrap" VerticalAlignment="Top" Width="253" TextChanged="TextBox_TextChanged" HorizontalAlignment="Left" Grid.Column="2" Grid.ColumnSpan="2"/>
                    <TextBox x:Name ="Profiletextbox" Height="20" Margin="8,170,13,0" TextWrapping="Wrap" VerticalAlignment="Top" Width="253" TextChanged="TextBox_TextChanged" HorizontalAlignment="Center" Grid.Column="2" Grid.ColumnSpan="2"/>
                    <TextBox x:Name ="Finishtextbox" Height="20" Margin="8,203,0,0" TextWrapping="Wrap" VerticalAlignment="Top" Width="253" TextChanged="TextBox_TextChanged" HorizontalAlignment="Left" Grid.Column="2" Grid.ColumnSpan="2"/>
                    <TextBlock HorizontalAlignment="Left" Margin="10,110,0,0" TextWrapping="Wrap" Text="Attributes" VerticalAlignment="Top" RenderTransformOrigin="-0.481,1.375" FontWeight="Bold" FontSize="16" Width="178" Grid.ColumnSpan="4"/>
                    <TextBlock HorizontalAlignment="Left" Margin="13,270,0,0" TextWrapping="Wrap" VerticalAlignment="Top" Width="54" RenderTransformOrigin="0.944,6.375" Text="Class" FontSize="14"/>
                    <TextBox x:Name ="Classtextbox" Height="21" Margin="8,270,13,0" TextWrapping="Wrap" VerticalAlignment="Top" Width="253" TextChanged="TextBox_TextChanged" HorizontalAlignment="Center" Grid.Column="2" Grid.ColumnSpan="2"/>
                    <TextBlock HorizontalAlignment="Left" Margin="13,317,0,0" TextWrapping="Wrap" Text="User-defined attributes" VerticalAlignment="Top" RenderTransformOrigin="-0.481,1.375" FontWeight="Bold" FontSize="16" Width="229" Grid.ColumnSpan="4"/>
                    <TextBlock HorizontalAlignment="Left" Margin="13,353,0,0" TextWrapping="Wrap" VerticalAlignment="Top" Width="98" RenderTransformOrigin="0.944,6.375" Text="Comment" FontSize="14"/>
                    <TextBlock HorizontalAlignment="Left" Margin="13,384,0,0" TextWrapping="Wrap" VerticalAlignment="Top" Width="154" RenderTransformOrigin="0.944,6.375" Text="Bought Out Item Name" FontSize="14" Grid.ColumnSpan="4"/>
                    <TextBox x:Name ="Boinametextbox" Height="21" Margin="62,382,0,0" TextWrapping="Wrap" VerticalAlignment="Top" Width="190" TextChanged="TextBox_TextChanged" HorizontalAlignment="Left" Grid.Column="3"/>
                    <TextBox x:Name ="Commenttextbox" Height="21" Margin="62,351,0,0" TextWrapping="Wrap" VerticalAlignment="Top" Width="190" TextChanged="TextBox_TextChanged" HorizontalAlignment="Left" FontSize="14" Grid.Column="3"/>
                    <TextBlock HorizontalAlignment="Left" Margin="10,10,0,0" TextWrapping="Wrap" VerticalAlignment="Top" RenderTransformOrigin="-0.481,1.375" Width="299" FontWeight="Bold" FontSize="16" Grid.ColumnSpan="4"><Run Text="Numbering series"/></TextBlock>
                    <TextBlock HorizontalAlignment="Left" Margin="10,55,0,0" TextWrapping="Wrap" Text="Part" VerticalAlignment="Top" RenderTransformOrigin="-0.481,1.375" Width="128" FontSize="14" Grid.ColumnSpan="4"/>
                    <TextBlock HorizontalAlignment="Left" Margin="10,84,0,0" TextWrapping="Wrap" Text="Assembly" VerticalAlignment="Top" RenderTransformOrigin="-0.481,1.375" Width="128" FontSize="14" Grid.ColumnSpan="4"/>
                    <TextBox x:Name ="Partprefixtextbox" Height="21" Margin="8,55,0,0" TextWrapping="Wrap" VerticalAlignment="Top" Width="80" TextChanged="TextBox_TextChanged" HorizontalAlignment="Left" Grid.ColumnSpan="2" Grid.Column="2"/>
                    <TextBox x:Name ="Assemblyprefixtextbox" Height="21" Margin="8,84,0,0" TextWrapping="Wrap" VerticalAlignment="Top" Width="80" TextChanged="TextBox_TextChanged" HorizontalAlignment="Left" RenderTransformOrigin="0.518,1" Grid.ColumnSpan="2" Grid.Column="2"/>
                    <TextBox x:Name ="Partstartnumbertextbox" Height="21" Margin="127,55,0,0" TextWrapping="Wrap" VerticalAlignment="Top" Width="126" TextChanged="TextBox_TextChanged" HorizontalAlignment="Left" Grid.Column="3"/>
                    <TextBox x:Name ="Assemblystartnumbertextbox" Height="21" Margin="127,84,0,0" TextWrapping="Wrap" VerticalAlignment="Top" Width="125" TextChanged="TextBox_TextChanged" HorizontalAlignment="Left" RenderTransformOrigin="0.501,1.292" Grid.Column="3"/>
                    <TextBlock HorizontalAlignment="Left" Margin="13,238,0,222" TextWrapping="Wrap" VerticalAlignment="Center" Width="54" RenderTransformOrigin="0.944,6.375" Text="Material" FontSize="14"/>
                    <TextBox x:Name ="Materialtextbox" Height="21" Margin="8,237,13,0" TextWrapping="Wrap" VerticalAlignment="Top" Width="253" TextChanged="TextBox_TextChanged" HorizontalAlignment="Center" Grid.Column="2" Grid.ColumnSpan="2"/>
                    <TextBlock Margin="10,31,-59,0" TextWrapping="Wrap" Text="Prefix:" VerticalAlignment="Top" RenderTransformOrigin="-0.481,1.375" FontSize="14" Grid.ColumnSpan="2" Grid.Column="2"/>
                    <TextBlock HorizontalAlignment="Left" Margin="127,31,0,0" TextWrapping="Wrap" Text="Start number:" VerticalAlignment="Top" RenderTransformOrigin="-0.481,1.375" Width="128" FontSize="14" Grid.Column="3"/>
                    <CheckBox Content="CheckBox_partstartnumber" x:Name="checkbox_partstartnumber" Grid.Column="3" HorizontalAlignment="Left" Margin="107,58,0,0" VerticalAlignment="Top" FontSize="0.01"/>
                    <CheckBox Content="CheckBox_assstartnumber" x:Name="checkbox_assstartnumber" Grid.Column="3" HorizontalAlignment="Left" Margin="107,87,0,0" VerticalAlignment="Top" FontSize="0.01"/>
                    <CheckBox Content="CheckBox_partprefix" x:Name="checkbox_partprefix" HorizontalAlignment="Left" Margin="108,58,0,0" VerticalAlignment="Top" FontSize="0.01" Grid.ColumnSpan="3"/>
                    <CheckBox Content="CheckBox_assprefix" x:Name="checkbox_assprefix" HorizontalAlignment="Left" Margin="108,87,0,0" VerticalAlignment="Top" FontSize="0.01" Grid.ColumnSpan="3"/>
                    <CheckBox Content="CheckBox_partname" x:Name="checkbox_partname" HorizontalAlignment="Left" Margin="108,139,0,0" VerticalAlignment="Top" FontSize="0.01" Grid.ColumnSpan="3"/>
                    <CheckBox Content="CheckBox_partprofile" x:Name="checkbox_partprofile" HorizontalAlignment="Left" Margin="108,172,0,0" VerticalAlignment="Top" FontSize="0.01" Grid.ColumnSpan="3"/>
                    <CheckBox Content="CheckBox_finish"  x:Name="checkbox_finish" HorizontalAlignment="Left" Margin="108,206,0,0" VerticalAlignment="Top" FontSize="0.01" Grid.ColumnSpan="3"/>
                    <CheckBox Content="CheckBox_material" x:Name ="checkbox_material" HorizontalAlignment="Left" Margin="108,240,0,0" VerticalAlignment="Top" FontSize="0.01" Grid.ColumnSpan="3"/>
                    <CheckBox Content="CheckBox_class" x:Name="checkbox_class" HorizontalAlignment="Left" Margin="108,273,0,0" VerticalAlignment="Top" FontSize="0.01" Grid.ColumnSpan="3"/>
                    <CheckBox Content="CheckBox_comment" x:Name="checkbox_comment"  HorizontalAlignment="Left" Margin="42,354,0,0" VerticalAlignment="Top" FontSize="0.01" Grid.Column="3"/>
                    <CheckBox Content="CheckBox_boi" x:Name="checkbox_boi" Margin="42,385,0,0" VerticalAlignment="Top" FontSize="0.01" Grid.Column="3"/>

                </Grid>
            </TabItem>
            <TabItem Header="Bolts" Margin="13,-2,-35,0">
                <Grid>
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="16*"/>
                        <ColumnDefinition Width="11*"/>
                        <ColumnDefinition Width="367*"/>
                    </Grid.ColumnDefinitions>
                    <TextBox x:Name="boltcutlengthtextbox" Margin="211,115,36,0" TextWrapping="Wrap" Text="TextBox" VerticalAlignment="Top" Width="120" Grid.Column="2"/>
                    <TextBlock HorizontalAlignment="Left" Margin="153,0,0,421" TextWrapping="Wrap" Text="Size" VerticalAlignment="Bottom" Grid.Column="2"/>
                    <TextBlock HorizontalAlignment="Left" Margin="127,69,0,0" TextWrapping="Wrap" VerticalAlignment="Top" RenderTransformOrigin="0.528,-0.47" Grid.Column="2"><Run Text="Standard"/></TextBlock>
                    <TextBlock HorizontalAlignment="Left" Margin="41,92,0,0" TextWrapping="Wrap" Text="Bolt type (site/workshop)" VerticalAlignment="Top" Grid.Column="2"/>
                    <TextBlock HorizontalAlignment="Left" Margin="10,16,0,0" TextWrapping="Wrap" VerticalAlignment="Top" RenderTransformOrigin="-0.481,1.375" Width="299" FontWeight="Bold" FontSize="16" Grid.ColumnSpan="3"><Run Text="Bolt"/></TextBlock>
                    <TextBlock HorizontalAlignment="Left" Margin="119,115,0,0" TextWrapping="Wrap" Text="Cut length" VerticalAlignment="Top" RenderTransformOrigin="0.541,-0.123" Grid.Column="2"/>
                    <TextBlock HorizontalAlignment="Left" Margin="111,140,0,0" TextWrapping="Wrap" Text="Extra length" VerticalAlignment="Top" Grid.Column="2"/>
                    <TextBox HorizontalAlignment="Left" Margin="211,92,0,0" TextWrapping="Wrap" Text="TextBox" VerticalAlignment="Top" Width="120" Grid.Column="2"/>
                    <TextBox x:Name="boltshapetextbox" HorizontalAlignment="Left" Margin="211,187,0,0" TextWrapping="Wrap" Text="TextBox" VerticalAlignment="Top" Width="120" Grid.Column="2"/>
                    <TextBlock HorizontalAlignment="Left" Margin="10,161,0,0" TextWrapping="Wrap" Text="Bolt group" VerticalAlignment="Top" RenderTransformOrigin="-0.481,1.375" Width="299" FontWeight="Bold" FontSize="16" Grid.ColumnSpan="3"/>
                    <TextBlock HorizontalAlignment="Left" Margin="141,188,0,0" TextWrapping="Wrap" Text="Shape" VerticalAlignment="Top" Grid.Column="2"/>
                    <TextBox x:Name="boltdistx"  HorizontalAlignment="Left" Margin="211,210,0,0" TextWrapping="Wrap" Text="TextBox" VerticalAlignment="Top" Width="120" Grid.Column="2"/>
                    <TextBox x:Name="boltdisty" Margin="211,233,36,0" TextWrapping="Wrap" Text="TextBox" VerticalAlignment="Top" Width="120" Grid.Column="2"/>
                    <TextBox x:Name ="boltextralengthtextbox" HorizontalAlignment="Left" Margin="211,140,0,0" TextWrapping="Wrap" Text="TextBox" VerticalAlignment="Top" Width="120" Grid.Column="2"/>
                    <TextBlock HorizontalAlignment="Left" Margin="10,263,0,0" TextWrapping="Wrap" Text="Holes" VerticalAlignment="Top" RenderTransformOrigin="-0.481,1.375" Width="299" FontWeight="Bold" FontSize="16" Grid.ColumnSpan="3"/>
                    <TextBox x:Name="bolttolerancetextbox" HorizontalAlignment="Left" Margin="211,288,0,0" TextWrapping="Wrap" Text="TextBox" VerticalAlignment="Top" Width="120" Grid.Column="2"/>
                    <TextBox x:Name="boltslottedtextbox" HorizontalAlignment="Left" Margin="211,312,0,0" TextWrapping="Wrap" Text="TextBox" VerticalAlignment="Top" Width="120" Grid.Column="2"/>
                    <TextBox x:Name="boltslothole_x_textbox" Margin="211,334,36,0" TextWrapping="Wrap" Text="TextBox" VerticalAlignment="Top" Width="120" Grid.Column="2"/>
                    <TextBox x:Name="boltslothole_y_textbox" Margin="211,358,36,0" TextWrapping="Wrap" Text="TextBox" VerticalAlignment="Top" Width="120" Grid.Column="2"/>
                    <TextBlock HorizontalAlignment="Left" Margin="120,211,0,0" TextWrapping="Wrap" Text="Bolt dist X" VerticalAlignment="Top" Grid.Column="2"/>
                    <TextBlock HorizontalAlignment="Left" Margin="120,234,0,0" TextWrapping="Wrap" Text="Bolt dist Y" VerticalAlignment="Top" RenderTransformOrigin="0.498,0.251" Grid.Column="2"/>
                    <TextBlock HorizontalAlignment="Left" Margin="123,289,0,0" TextWrapping="Wrap" Text="Tolerance" VerticalAlignment="Top" RenderTransformOrigin="0.498,0.251" Grid.Column="2"/>
                    <TextBlock HorizontalAlignment="Left" Margin="135,313,0,0" TextWrapping="Wrap" Text="Slotted" VerticalAlignment="Top" RenderTransformOrigin="0.498,0.251" Grid.Column="2"/>
                    <TextBlock HorizontalAlignment="Left" Margin="99,335,0,0" TextWrapping="Wrap" Text="Slotted hole X" VerticalAlignment="Top" RenderTransformOrigin="0.498,0.251" Grid.Column="2"/>
                    <TextBlock HorizontalAlignment="Left" Margin="99,359,0,0" TextWrapping="Wrap" Text="Slotted hole Y" VerticalAlignment="Top" RenderTransformOrigin="0.498,0.251" Grid.Column="2"/>
                    <UIControls:WpfBoltCatalogSize x:Name="boltcatalogsize" HorizontalAlignment="Left" Margin="211,39,0,0" VerticalAlignment="Top" Width="120" Grid.Column="2" ItemsSource="{Binding BoltSizes, ElementName=boltcatalog_standard}"/>
                    <UIControls:WpfBoltCatalogStandard x:Name="boltcatalog_standard"   HorizontalAlignment="Left" Margin="211,66,0,0" VerticalAlignment="Top" Width="120" Grid.Column="2" />
                    <CheckBox Content="CheckBox_size" x:Name="checkbox_boltsize" Grid.Column="2" HorizontalAlignment="Left" Margin="186,43,0,0" VerticalAlignment="Top" FontSize="0.01"/>
                    <CheckBox Content="CheckBox_standard" x:Name="checkbox_boltstandard" Grid.Column="2" HorizontalAlignment="Left" Margin="186,70,0,0" VerticalAlignment="Top" FontSize="0.01"/>
                    <CheckBox Content="CheckBox_bolttype" x:Name="checkbox_bolttype" Grid.Column="2" HorizontalAlignment="Left" Margin="186,94,0,0" VerticalAlignment="Top" FontSize="0.01"/>
                    <CheckBox Content="CheckBox_cutlength" x:Name="checkbox_cutlength" Grid.Column="2" HorizontalAlignment="Left" Margin="186,117,0,0" VerticalAlignment="Top" FontSize="0.01"/>
                    <CheckBox Content="CheckBox_extralength" x:Name="checkbox_extralength" Grid.Column="2" HorizontalAlignment="Left" Margin="186,142,0,0" VerticalAlignment="Top" FontSize="0.01"/>
                    <CheckBox Content="CheckBox_shape" x:Name="checkbox_shape" Grid.Column="2" HorizontalAlignment="Left" Margin="186,189,0,0" VerticalAlignment="Top" FontSize="0.01"/>
                    <CheckBox Content="CheckBox_boltdistx" x:Name="checkbox_boltdistx" Grid.Column="2" HorizontalAlignment="Left" Margin="186,212,0,0" VerticalAlignment="Top" FontSize="0.01"/>
                    <CheckBox Content="CheckBox_boltdisty" x:Name="checkbox_boltdisty" Grid.Column="2" HorizontalAlignment="Left" Margin="186,235,0,0" VerticalAlignment="Top" FontSize="0.01"/>
                    <CheckBox Content="CheckBox_tolerance" x:Name="checkbox_tolerance" Grid.Column="2" HorizontalAlignment="Left" Margin="186,289,0,0" VerticalAlignment="Top" FontSize="0.01"/>
                    <CheckBox Content="CheckBox_slotted" x:Name="checkbox_slotted" Grid.Column="2" HorizontalAlignment="Left" Margin="186,314,0,0" VerticalAlignment="Top" FontSize="0.01"/>
                    <CheckBox Content="CheckBox_slotholex" x:Name="checkbox_slotholex" Grid.Column="2" HorizontalAlignment="Left" Margin="186,336,0,0" VerticalAlignment="Top" FontSize="0.01"/>
                    <CheckBox Content="CheckBox_slotholeY" x:Name="checkbox_slotholey" Grid.Column="2" HorizontalAlignment="Left" Margin="186,360,0,0" VerticalAlignment="Top" FontSize="0.01"/>

                </Grid>
            </TabItem>

        </TabControl>

        <Button Content="Modify" HorizontalAlignment="Left" Margin="232,450,0,-49" Width="146" Click="Button_Click" RenderTransformOrigin="0.5,0.5" Height="39" VerticalAlignment="Top">
            <Button.RenderTransform>
                <TransformGroup>
                    <ScaleTransform/>
                    <SkewTransform/>
                    <RotateTransform Angle="0.084"/>
                    <TranslateTransform/>
                </TransformGroup>
            </Button.RenderTransform>
        </Button>
        <Button Content="Clear all fields" HorizontalAlignment="Left" Height="38" Margin="29,450,0,-48" VerticalAlignment="Top" Width="138" Click="Button_Click_1"/>
    </Grid>
</Window>
